name: "Test project with pnpm"
description: "Installs pnpm and runs pnpm test"
inputs:
  pnpm-version:
    description: "Version of pnpm to install"
    required: false
    default: "8.15.4"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"
  install-pnpm:
    description: "Whether to install pnpm before running tests"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      if: ${{ inputs.install-pnpm == true }}
      uses: RoyalVoluntaryService/library-workflow-actions/typescript/install-pnpm@main
      with:
        version: ${{ inputs.pnpm-version }}
        node-version: ${{ inputs.node-version }}

    - name: Run Test Suite
      run: pnpm test
      shell: bash
