name: "Build project with optional tests"
description: "Installs pnpm, optionally tests, then builds"
inputs:
  pnpm-version:
    description: "Version of pnpm to install"
    required: false
    default: "8.15.4"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"
  run-tests:
    description: "Whether to run tests before building"
    required: false
    default: true
  extra-env:
    description: "Comma-separated env assignments (e.g. VAR1=value1,VAR2=value2)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: RoyalVoluntaryService/library-workflow-actions/typescript/install-pnpm@main
      with:
        version: ${{ inputs.pnpm-version }}
        node-version: ${{ inputs.node-version }}
        
    - if: ${{ inputs.run-tests == 'true' }}
      uses: RoyalVoluntaryService/library-workflow-actions/typescript/run-tests@main
      with:
        pnpm-version: ${{ inputs.pnpm-version }}
        node-version: ${{ inputs.node-version }}
        install-pnpm: false

    - name: Export Extra Env Vars
      shell: bash
      run: |
        if [[ -n "${{ inputs.extra-env }}" ]]; then
          echo "${{ inputs.extra-env }}" | tr ',' '\n' | while IFS='=' read -r key value; do
            echo "Exporting $key"
            echo "$key='$value'" >> "$GITHUB_ENV"
          done
        fi
        
    - name: Build Project
      shell: bash
      run: |
        env
        pnpm build
